baseurl = "https://shenweiyan.github.io/ICS-Hugo-Theme/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "zh-cn"	                  # html的lang属性值
DefaultContentLanguage = "zh-cn"   	  # 默认内容语言用于选择i18n语言模板
title = "ICS-Hugo-Theme | Bio IT 爱好者"
theme = "ICS-Hugo-Theme"
#googleAnalytics = "UA-112592341-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true                             # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" 			  # format of a new post
enableGitInfo = false
publishDir = "docs"


[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 3

[[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 4

[[menu.main]]
    name = "简历"
    url = "/resume/shenweiyan"
    weight = 5

[[menu.main]]
    name = "乱弹"
    url = "/tweets/"
    weight = 6

[[menu.main]]
    name = "留言"
    url = "/feedback/"
    weight = 7

[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 8

[[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 9


[params]
    siteurl     = "https://shenweiyan.github.io/ICS-Hugo-Theme/"
    description = "Welcome to the blog site of Steven Shen."
    disqusURL   = "https://shenweiyan.github.io/home/"
    customJS    = []
    githubContentURL = "https://github.com/shenweiyan/ICS-Hugo-Theme/edit/main/content/"
    highlightjsTheme = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/github.min.css"
    dateFormat  = "2019-01-01"			# "2019-01-01, Mon, "
    loadTypekit = false
    recentPosts = true    			# 首页最近更新文章
    fancybox    = true
    baiduSiteVerificateID = "code-HxM5pCr1nD"   # 百度搜索资源平台HTML标签验证码

[params.footer]
    copyright = "<br/><br/>&copy; Powered by [ICS-Hugo-Theme](https://github.com/shenweiyan/ICS-Hugo-Theme) and [Hugo](https://gohugo.io) | [Bio IT 爱好者](https://www.bioitee.com/) 2018 - {year} | [粤ICP备16023717号](http://beian.miit.gov.cn/)<br/>"
    moreinfo = "<br/><br/>[![yuque](https://img.shields.io/badge/沈维燕-语雀知识库-blueviolet)](https://www.yuque.com/shenweiyan) [![wechat](https://img.shields.io/badge/沈维燕-微信公众号-important)](https://apps-db.oss-cn-shenzhen.aliyuncs.com/bioitee/bioitee.png) [![zhihu](https://img.shields.io/badge/沈维燕-知乎-blue)](https://www.zhihu.com/people/shenweiyan) [![bioitee](https://img.shields.io/badge/沈维燕-BioIT爱好者-green)](https://www.bioitee.com/)"

[params.author]
    en = "Steven Shum"
    cn = "沈维燕"

[params.logo.en]
    img = "https://apps-db.oss-cn-shenzhen.aliyuncs.com/logos/shenweiyan.png"
    url = "/"
    alt = "Steven Shum"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"

#disqusShortname = "shen-bioinit" # 关闭 disqus 评论
[params.utteranc]
    enable = true
    repo = "shenweiyan/issues"    # utteranc 的评论默认存储在 github，这里填写你的 github repo，格式为 owner/repo
    issueTerm = "title"           # 表示你选择以那种方式让github issue的评论和你的文章关联可以选择默认的 pathname。
    theme = "github-light"        # 样式主题


[taxonomies]
    tag = "tags"
    series = "series"
    category = "categories"

[markup.goldmark.renderer]
    unsafe= true
